# serverless.yml

service: responses

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /response
          resp: json
          authorizer: aws_iam
      - http:
          method: POST
          path: /response
          resp: json
          authorizer: aws_iam

plugins:
  - serverless-offline

resources:
  Resources:
    ServerlessRDSCluster:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: Postgres

custom:
  serverless-offline:
    port: 4001
